- ESSArch_TA/frontend/static/frontend/styles/styles.scss
Required for brand icons like windows logo
> Add brand icons import

- ESSArch_TA/frontend/static/frontend/styles/modules/index.scss
> Move styles to core

- ESSArch_TA/frontend/static/frontend/styles/modules/index.scss
- ESSArch_TA/frontend/static/frontend/styles/modules/receive_sip.scss
- ESSArch_TA/frontend/static/frontend/styles/modules/workspace.scss
- ESSArch_TA/frontend/static/frontend/views/administration.html
- ESSArch_TA/frontend/static/frontend/views/receive_sip_reception.html
- ESSArch_TA/frontend/static/frontend/views/receive_sip_transfer_sip.html
- ESSArch_TA/frontend/static/frontend/views/workarea.html
Fix bug where content views would appear under the filters
> Fix layout bug

- ESSArch_TA/frontend/static/frontend/views/home.html
Use whole button as dropdown toggle and only use one popover
> Update user dropdown

- .travis.yml
- ESSArch_TA/frontend/static/frontend/package.json
- ESSArch_TA/frontend/static/frontend/yarn.lock
> Use single-run with spec report as default yarn test script

- ESSArch_TA/frontend/static/frontend/scripts/controllers/ConfirmReceiveCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/DataModalInstanceCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/FilebrowserController.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/ImportCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/ProfileCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/ReceptionCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/WorkareaValidationCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/services/listViewService.js
- ESSArch_TA/static/lang/en.json
- ESSArch_TA/static/lang/sv.json
Check for error codes that has general messages to prevent double error messages. Add translations for all frontend generated messages
> Add better error handling

- ESSArch_TA/frontend/static/frontend/views/home.html
- ESSArch_TA/static/lang/en.json
- ESSArch_TA/static/lang/sv.json
> Add message and disable dropdown if a user has no organizations

- ESSArch_TA/ip/filters.py
- ESSArch_TA/ip/views.py
See the [Migration Guide](https://django-filter.readthedocs.io/en/master/guide/migration.html#migrating-to-2-0) and the [Release Notes](https://github.com/carltongibson/django-filter/blob/2.0.0/CHANGES.rst) for changes in 2.0
> Add support for Django Filter 2.0

- ESSArch_TA/frontend/static/frontend/scripts/controllers/AppCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/services/myService.js
- ESSArch_TA/frontend/static/frontend/views/columns/column_state.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_status.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_step_state.html
- ESSArch_TA/static/lang/en.json
- ESSArch_TA/static/lang/sv.json
* Remove step state columns
* Add more colors to progressbars
> Redesing step state indicators

- ESSArch_TA/frontend/static/frontend/styles/modules/index.scss
- ESSArch_TA/frontend/static/frontend/styles/styles.scss
- ESSArch_TA/static/lang/en.json
- ESSArch_TA/static/lang/sv.json
> Move import styling to core and add translations

- ESSArch_TA/frontend/static/frontend/views/profile_editor.html
Remove usage of old lock-button and replace it with more appropriate btn-small.
> Use new class for small buttons

- ESSArch_TA/static/lang/en.json
- ESSArch_TA/static/lang/sv.json
Re-add translation after removing it because it was used more than once
> Add translation for missing validation profile

- ESSArch_TA/frontend/static/frontend/styles/modules/profile_editor.scss
- ESSArch_TA/frontend/static/frontend/views/list_view_table.html
- ESSArch_TA/frontend/static/frontend/views/profile_editor.html
- ESSArch_TA/frontend/static/frontend/views/transfer_sip_modal.html
> Adjust button colors

- ESSArch_TA/frontend/static/frontend/scripts/essarch.module.js
- ESSArch_TA/frontend/static/frontend/views/columns/column_delete.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_end_date.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_label.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_object_identifier_value.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_start_date.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_state.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_status.html
- ESSArch_TA/frontend/static/frontend/views/filebrowser.html
- ESSArch_TA/frontend/static/frontend/views/form_template_input.html
- ESSArch_TA/frontend/static/frontend/views/form_template_select.html
- ESSArch_TA/frontend/static/frontend/views/home.html
- ESSArch_TA/frontend/static/frontend/views/list_view_table.html
- ESSArch_TA/frontend/static/frontend/views/profile_editor.html
- ESSArch_TA/frontend/static/frontend/views/support.html
- ESSArch_TA/frontend/static/frontend/views/validation_fullscreen_message.html
- ESSArch_TA/frontend/static/frontend/views/workarea_transformation.html
- ESSArch_TA/frontend/static/frontend/views/workarea_validation.html
* Add global delay for tooltips and popovers
* Change from popovers to tooltips where suited
* Use auto placement so that tooltips and popovers does not go outside
the screen. The have a default position but it will be re-evaluated if
original placement is outside the screen.
> Change popovers to tooltips and add global delay

- ESSArch_TA/ip/tests/test_ips.py
- ESSArch_TA/preingest/tests/test_real_tasks.py
`mock` is built-in to Python since 3.3: https://docs.python.org/3/whatsnew/3.3.html
> Use built-in mock

- ESSArch_TA/frontend/static/frontend/scripts/controllers/ConfirmReceiveCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/DataModalInstanceCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/FilebrowserController.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/OverwriteModalInstanceCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/ProfileCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/ReceptionCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/WorkareaValidationCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/services/listViewService.js
* Remove ErrorResponse module
* Let error response notifications be controlled by http interceptor in Core
> Use http-interceptor for error response notifications

- ESSArch_TA/frontend/static/frontend/views/workarea_transformation.html
- ESSArch_TA/frontend/static/frontend/views/workarea_validation.html
Add ng-if's to prevent filebrowser from making requests while othe tab is open
> Isolate filebrowser tab

- ESSArch_TA/frontend/static/frontend/scripts/controllers/BaseCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/ReceptionCtrl.js
- ESSArch_TA/frontend/static/frontend/scripts/controllers/WorkareaCtrl.js
Use selected IP updater to update selected IPs when IP list is refreshed
> Use selected IP updater

- ESSArch_TA/frontend/static/frontend/styles/modules/index.scss
> Remove duplicate CSS class definition

- ESSArch_TA/frontend/static/frontend/views/columns/column_archival_institution.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_archivist_organization.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_create_date.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_delete.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_end_date.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_entry_date.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_label.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_object_identifier_value.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_object_size.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_responsible.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_start_date.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_state.html
- ESSArch_TA/frontend/static/frontend/views/columns/column_status.html
- ESSArch_TA/frontend/static/frontend/views/list_view_table.html
- ESSArch_TA/frontend/static/frontend/views/transfer_sip_modal.html
* Move click functionality to row instead of columns
* Delete button still works as axpected
* Use selectable row class for selectable table rows
> Improve table row selection

- ESSArch_TA/frontend/static/frontend/scripts/controllers/UtilCtrl.js
- ESSArch_TA/frontend/static/frontend/views/home.html
Sometimes the logo section is displayed though there is no logo to show.
> Fix bug with logo visibility

- ESSArch_TA/profiles/views.py
Not used since https://github.com/ESSolutions/ESSArch_Tools_Archive/commit/2781151b3a7cca9ca56d9d1ff18e2766b0cc7acd
> Remove unused ProfileIPViewSet
